server:
    port: 8081
    servlet:
      jsp:
        init-parameters:
          development: true
      context-path: /

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/tgw?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: asdQWE123
      initial-size: 20
      min-idle: 20
      max-active: 100
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    enabled: false
  mvc:
      view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
  profiles:
    # test,dev,prod
    active: prod
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  #typeAliasesPackage: com.example.mybaitsxml.dao.entity
  mapperLocations: classpath*:com/tgw/**/*.xml
  #configLocation: classpath:config/mybatis-config.xml

mapper:
    mappers:
        - com.tgw.basic.framework.baseMapper.BaseModelMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    dialect: mysql
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: false
    params: count=countSql
    offset-as-page-num: true
    rowBoundsWithCount: true
    page-size-zero: true
    returnPageInfo: none

logging:
  config: classpath:config/logback-spring.xml
dubbo:
  application:
    name: basic-main-web
  registry:
    address: zookeeper://127.0.0.1:2181
    #address: redis://127.0.0.1:6379
    check: false
  #reference:
    #check: false
